### ISSUE TITLE
click on scrollbar in ie11 causes dropdown to close

### ISSUE THREAD

**Issue by zezulka000** [devbridge/jQuery-Autocomplete#602] opened 2017-04-06 13:40 UTC
click on scrollbar in ie11 causes dropdown to close

**Comment by philwig** [comment] 2017-08-31 10:05
Actually this is all of IE, not just IE11.

This is a serious issue, introduced in this current (1.4.1) version. It fails because on IE a blur event is fired when the user clicks the scrollbar. You don't get the blur event for other browsers.

The issue is caused by all IE (except for Edge!) treating the scroll bar as "outside" the element, so it fires the blur event, and that makes this plugin not work.

**Comment by Jojoshua** [comment] 2017-09-15 15:01
I cannot use this plugin for the same reason. Which version did not have this issue?

**Comment by philwig** [comment] 2017-09-15 15:19
;-) The previous one we used. But this is fixable... my mate Ant did it as follows, although he also points out that there is probably a reason they didn't write it this way in the first place, so this may be a bad idea for reasons we don't know. It works fine for our customers though, so far...

 **Autocomplete: Change the way the suggestions box is closed.. Fixes issues**
- Suggestions box closing on IE when scroll bar is clicked due to IE considering scrollbar click a loss of focus (HA-077-66639)
- Timing dependent bugs where box closes due to close handler not being aborted within 200ms


@@ -211,14 +211,14 @@
            $(window).on('resize.autocomplete', that.fixPositionCapture);
            that.el.on('keydown.autocomplete', function (e) { that.onKeyPress(e); });
            that.el.on('keyup.autocomplete', function (e) { that.onKeyUp(e); });
            - that.el.on('blur.autocomplete', function () { that.onBlur(); });
             +$('body').on('mousedown.autocomplete', function (e) { that.onMouseDown(e); });
             that.el.on('focus.autocomplete', function () { that.onFocus(); });
             that.el.on('change.autocomplete', function (e) { that.onKeyUp(e); });
             that.el.on('input.autocomplete', function (e) { that.onKeyUp(e); });
         },
         onFocus: function () {
             var that = this;

@@ -227,18 +227,20 @@
             if (that.el.val().length >= that.options.minChars) {
                 that.onValueChange();
             }
         },

        - onBlur: function () {
       + onMouseDown: function (e) {
             var that = this;

       -// If user clicked on a suggestion, hide() will
       -// be canceled, otherwise close suggestions
       -that.blurTimeoutId = setTimeout(function () {
       -that.hide();
       - }, 200);
       +// Ignore clicks inside the input or suggestion boxes (e.g. scroll bar being clicked)
       +if ($(e.target).closest('.autocomplete-suggestions').length > 0 ||
       +$(e.target).closest(that.el).length) {
       +     return;
       + }
       +
       + that.hide();
         },

**Comment by Jojoshua** [comment] 2017-09-15 15:29
Thanks, that does seem to work.

**Comment by jamesond** [comment] 2017-10-03 14:36
Where does this code need to go to fix the issue?

**Comment by kugijp** [comment] 2017-11-09 13:16
In the above code, if you do not select anything from the list, the container will remain displayed even if you out focus. So, I responded with the following fix-code.

```diff
@@ -201,6 +201,11 @@
                 clearTimeout(that.blurTimeoutId);
             })
 
+            container.on('focus.autocomplete', function () {
+                clearTimeout(that.blurTimeoutId);
+                that.el.focus();
+            })
+
             that.fixPositionCapture = function () {
                 if (that.visible) {
                     that.fixPosition();
```

**Comment by CZahrobsky** [comment] 2018-05-09 18:42
We had this issue when I had set the overflow-y style to 'scroll'  ...
When I constrained the pop-up with a max-height size and set the overflow-y style to visible, it corrected the scrollbar focus issue in IE 11, all without any scripting!  

```
ul.ui-autocomplete.ui-menu 
{
    max-height: 12em;
    overflow-x: hidden;
    overflow-y: visible;
}
```

**Closed** 2018-09-20 14:45 UTC

**Comment by ritugnr30** [comment] 2020-07-29 13:53
> ;-) The previous one we used. But this is fixable... my mate Ant did it as follows, although he also points out that there is probably a reason they didn't write it this way in the first place, so this may be a bad idea for reasons we don't know. It works fine for our customers though, so far...
> 
> **Autocomplete: Change the way the suggestions box is closed.. Fixes issues**
> 
> * Suggestions box closing on IE when scroll bar is clicked due to IE considering scrollbar click a loss of focus (HA-077-66639)
> * Timing dependent bugs where box closes due to close handler not being aborted within 200ms
> 
> @@ -211,14 +211,14 @@
> $(window).on('resize.autocomplete', that.fixPositionCapture);
> that.el.on('keydown.autocomplete', function (e) { that.onKeyPress(e); });
> that.el.on('keyup.autocomplete', function (e) { that.onKeyUp(e); });
> - that.el.on('blur.autocomplete', function () { that.onBlur(); });
> +$('body').on('mousedown.autocomplete', function (e) { that.onMouseDown(e); });
> that.el.on('focus.autocomplete', function () { that.onFocus(); });
> that.el.on('change.autocomplete', function (e) { that.onKeyUp(e); });
> that.el.on('input.autocomplete', function (e) { that.onKeyUp(e); });
> },
> onFocus: function () {
> var that = this;
> 
> @@ -227,18 +227,20 @@
> if (that.el.val().length >= that.options.minChars) {
> that.onValueChange();
> }
> },
> 
> ```
>     - onBlur: function () {
>    + onMouseDown: function (e) {
>          var that = this;
> 
>    -// If user clicked on a suggestion, hide() will
>    -// be canceled, otherwise close suggestions
>    -that.blurTimeoutId = setTimeout(function () {
>    -that.hide();
>    - }, 200);
>    +// Ignore clicks inside the input or suggestion boxes (e.g. scroll bar being clicked)
>    +if ($(e.target).closest('.autocomplete-suggestions').length > 0 ||
>    +$(e.target).closest(that.el).length) {
>    +     return;
>    + }
>    +
>    + that.hide();
>      

> ;-) The previous one we used. But this is fixable... my mate Ant did it as follows, although he also points out that there is probably a reason they didn't write it this way in the first place, so this may be a bad idea for reasons we don't know. It works fine for our customers though, so far...
> 
> **Autocomplete: Change the way the suggestions box is closed.. Fixes issues**
> 
> * Suggestions box closing on IE when scroll bar is clicked due to IE considering scrollbar click a loss of focus (HA-077-66639)
> * Timing dependent bugs where box closes due to close handler not being aborted within 200ms
> 
> @@ -211,14 +211,14 @@
> $(window).on('resize.autocomplete', that.fixPositionCapture);
> that.el.on('keydown.autocomplete', function (e) { that.onKeyPress(e); });
> that.el.on('keyup.autocomplete', function (e) { that.onKeyUp(e); });
> - that.el.on('blur.autocomplete', function () { that.onBlur(); });
> +$('body').on('mousedown.autocomplete', function (e) { that.onMouseDown(e); });
> that.el.on('focus.autocomplete', function () { that.onFocus(); });
> that.el.on('change.autocomplete', function (e) { that.onKeyUp(e); });
> that.el.on('input.autocomplete', function (e) { that.onKeyUp(e); });
> },
> onFocus: function () {
> var that = this;
> 
> @@ -227,18 +227,20 @@
> if (that.el.val().length >= that.options.minChars) {
> that.onValueChange();
> }
> },
> 
> ```
>     - onBlur: function () {
>    + onMouseDown: function (e) {
>          var that = this;
> 
>    -// If user clicked on a suggestion, hide() will
>    -// be canceled, otherwise close suggestions
>    -that.blurTimeoutId = setTimeout(function () {
>    -that.hide();
>    - }, 200);
>    +// Ignore clicks inside the input or suggestion boxes (e.g. scroll bar being clicked)
>    +if ($(e.target).closest('.autocomplete-suggestions').length > 0 ||
>    +$(e.target).closest(that.el).length) {
>    +     return;
>    + }
>    +
>    + that.hide();
>      },
> ```

**Comment by ritugnr30** [comment] 2020-07-29 14:12
Hi,
i am new to the coding. i am facing same scrollbar issue in IE with AutoCompleteExtender. I came across your solution. I want to give it a try. But not able to understand properly the code written.. 
What is "that" in **$(window).on('resize.autocomplete', that.fixPositionCapture);** and other subsequent lines.

Are below lines commented ? actually i am confused about this '+' symbol at the start of lines
   - onBlur: function () {
   + onMouseDown: function (e) {
         var that = this;
   -// If user clicked on a suggestion, hide() will
   -// be canceled, otherwise close suggestions
   -that.blurTimeoutId = setTimeout(function () {
   -that.hide();
   - }, 200);
   +// Ignore clicks inside the input or suggestion boxes (e.g. scroll bar being clicked)
   +if ($(e.target).closest('.autocomplete-suggestions').length > 0 ||
   +$(e.target).closest(that.el).length) {
   +     return;
   + }
   +
   + that.hide();
     },
